apiVersion: v1
kind: Service
metadata:
  name: sofia-ai
  namespace: magicsaas-staging
  labels:
    app: sofia-ai
    component: brain
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sofia-ai
---
apiVersion: v1
kind: Service
metadata:
  name: sofia-ai-headless
  namespace: magicsaas-staging
  labels:
    app: sofia-ai
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sofia-ai
