apiVersion: v1
kind: Namespace
metadata:
  name: magicsaas-staging
  labels:
    name: magicsaas-staging
    environment: staging
    project: magicsaas-system-infinity
---
apiVersion: v1
kind: Namespace
metadata:
  name: magicsaas-production
  labels:
    name: magicsaas-production
    environment: production
    project: magicsaas-system-infinity
